import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState } from "react";
import { Hero } from "../../components/Auth/Hero";
import { Wave } from "../../components/Auth/Wave";
import { CreateUserInput } from "../../schema/user.schema";
import { trpc } from "../../utils/trpc";

const SignUpPage: NextPage = () => {
  const router = useRouter();

  const { mutate, error } = trpc.useMutation(["user.register-user"], {
    onSuccess: () => {
      router.push("/");
    },
  });

  const [user, setUser] = useState({
    firstName: "",
    lastName: "",
    username: "",
    email: "",
    password: "",
  });

  function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();

    mutate(user);
  }

  function handleUserInputChange(e: React.ChangeEvent<HTMLInputElement>) {
    const { name, value } = e.target;

    setUser({
      ...user,
      [name]: value,
    } as Pick<CreateUserInput, keyof CreateUserInput>);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white relative">
        <div className="container flex flex-col items-center justify-center min-h-screen p-10 px-0 mx-auto md:py-20 md:p-10 md:px-0">
          <h1 className="font-extrabold text-center text-7xl">
            Create <span className="text-blue-500">T3</span> App
          </h1>
          <h2 className="mt-14 font-extrabold text-center text-4xl">Sign up</h2>

          <div className="mt-4">
            <form onSubmit={onSubmit}>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label
                    htmlFor="email"
                    className="block mb-2 text-sm text-gray-600"
                  >
                    First name
                  </label>
                  <input
                    type="text"
                    name="firstName"
                    id="firstName"
                    placeholder="Jane"
                    value={user.firstName}
                    onChange={handleUserInputChange}
                    className="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40"
                  />
                </div>
                <div>
                  <label
                    htmlFor="email"
                    className="block mb-2 text-sm text-gray-600"
                  >
                    Last name
                  </label>
                  <input
                    type="text"
                    name="lastName"
                    id="lastName"
                    placeholder="Doe"
                    value={user.lastName}
                    onChange={handleUserInputChange}
                    className="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40"
                  />
                </div>
              </div>
              <div className="mt-4">
                <label
                  htmlFor="email"
                  className="block mb-2 text-sm text-gray-600"
                >
                  Username
                </label>
                <input
                  type="text"
                  name="username"
                  autoComplete="no"
                  id="username"
                  placeholder="JaneD"
                  value={user.username}
                  onChange={handleUserInputChange}
                  className="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40"
                />
              </div>
              <div className="mt-4">
                <label
                  htmlFor="email"
                  className="block mb-2 text-sm text-gray-600"
                >
                  Email address
                </label>
                <input
                  autoComplete="email"
                  type="email"
                  name="email"
                  id="email"
                  placeholder="janedoe@example.com"
                  value={user.email}
                  onChange={handleUserInputChange}
                  className="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40"
                />
              </div>

              <div className="mt-4">
                <div className="flex justify-between mb-2">
                  <label htmlFor="password" className="text-sm text-gray-600">
                    Password
                  </label>
                </div>
                <input
                  autoComplete="password"
                  type="password"
                  name="password"
                  id="password"
                  placeholder="Your password"
                  value={user.password}
                  onChange={handleUserInputChange}
                  className="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40"
                />
              </div>
              {error && <p className="mt-3 text-red-500">{error.message}</p>}

              <div className="mt-6">
                <button className="w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform  bg-blue-500 hover:bg-blue-700 rounded-md hover:brand-green-alternative focus:outline-none focus:bg-blue-400 focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                  Sign up
                </button>
              </div>
            </form>

            <p className="mt-6 text-sm text-center text-gray-400">
              Already have an account?{" "}
              <Link
                className="cursor-pointer focus:outline-none focus:underline hover:underline"
                href="/"
              >
                <a className="text-blue-500 cursor-pointer focus:outline-none focus:underline hover:underline">
                  Log in
                </a>
              </Link>
              .
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default SignUpPage;
